1- https://github.com/dssg-pt/covid19pt-data

2- A nossa escolha incide sobre a temática generalizada da saúde, nomeadamente nos dados referentes ao Covid-19, uma vez que se apresenta algo bastante atual e interessante para a população em geral.

3- Consultar o ficheiro : "README-ANARITAHUGOMIGUELTOBBACK.md"

4- Para carregar o conjunto de dados utilizar o seguinte código: pd.read_csv("data.csv")
                                                                    df = pd.read_csv("data.csv") 
    Para apresentar as 10 primeiras linhas do conjunto de dados utilizar o seguinte código: df.head(10)

5- O ficheiro CSV recorre a dados do tipo DataFrame ou TextParser (de acordo com a página fornecida pelo professor: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html%22)

In [20]:
#Para apresentar as 10 primeiras linhas de código
import csv
import numpy as np
import pandas as pd
pd.read_csv("data.csv")
df = pd.read_csv("data.csv") 
data = open("data.csv","r")
data = pd.read_csv(data,nrows=9)
df.head(10)

,data,data_dados,confirmados,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,obitos_f,obitos_m
0,26-02-2020,26-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,27-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,28-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,29-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,01-03-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,02-03-2020,02-03-2020 00:00,2,2,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,03-03-2020,03-03-2020 16:00,4,2,1,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,04-03-2020,04-03-2020 17:00,6,3,1,2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,05-03-2020,05-03-2020 17:00,9,5,1,3,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,06-03-2020,06-03-2020 17:00,13,8,1,4,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN